from aiocoap import Message
from typing import Callable, Awaitable, Union, List, Tuple

class Resource:
    def __init__(self) -> None: ...
    
    async def render_get(self, request: Message) -> Message: ...
    async def render_post(self, request: Message) -> Message: ...

class Site(Resource):
    def __init__(self) -> None: ...
    def add_resource(self, path: Union[List[str], Tuple[str, ...]], resource: Resource) -> None: ...
    async def render(self, request: Message) -> Message: ...

ResourceHandler = Callable[[Message], Awaitable[Message]]