services:
  outpost:
    build: .
    environment:
      - DEBUG=$DEBUG
      - OUTPOST_PSK=${OUTPOST_PSK}
    ports:
      - "5683:5683/udp"
    volumes:
      - ./logs:/var/log
    restart: unless-stopped
  
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres_postgis
    environment:
      POSTGRES_DB: outpost
      POSTGRES_USER: outpost
      POSTGRES_PASSWORD: outpost
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U outpost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local